-- 1. Create Tutes Table
CREATE TABLE IF NOT EXISTS public.tutes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    file_url TEXT NOT NULL,
    is_free BOOLEAN DEFAULT FALSE,
    price DECIMAL(10, 2) DEFAULT 0,
    target_audience TEXT DEFAULT 'All Students',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Tute Enrollments Table (For Paid Tutes)
CREATE TABLE IF NOT EXISTS public.tute_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    tute_id BIGINT REFERENCES public.tutes(id) ON DELETE CASCADE,
    slip_url TEXT,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(student_id, tute_id)
);

-- 3. Enable RLS
ALTER TABLE public.tutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tute_enrollments ENABLE ROW LEVEL SECURITY;

-- 4. Policies for Tutes
CREATE POLICY "Public read for all tutes" ON public.tutes FOR SELECT USING (true);
CREATE POLICY "Admin full access for tutes" ON public.tutes FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 5. Policies for Tute Enrollments
CREATE POLICY "Students see their own tute enrollments" ON public.tute_enrollments FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Students create their own tute enrollments" ON public.tute_enrollments FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Admin full access for tute enrollments" ON public.tute_enrollments FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
